### ISSUE TITLE
Typo in src

### ISSUE THREAD

**Issue by hellobrophy** [jylauril/jquery-runner#13]
Typo on line 30, should read;

})(this, '_requestAnimationFrame');

**Comment by jylauril** [comment]
Sorry, but it's not a typo.

The purpose of that little closure there is to normalize the requestAnimationFrame function for older browsers: https://developer.mozilla.org/en-US/docs/Web/API/window.requestAnimationFrame

```
requestID = window.requestAnimationFrame(callback);       // Firefox 23 / IE 10 / Chrome / Safari 7 (incl. iOS)
requestID = window.mozRequestAnimationFrame(callback);    // Firefox < 23
requestID = window.webkitRequestAnimationFrame(callback); // Older versions of Safari / Chrome
```

What my code does it tries to prepend the 'mozR' or 'webkitR' or 'msR' or just 'r' into the partial 'equestAnimationFrame', thus forming the alternative, browser specific versions of that function name.

I know it's not very clear, but it was just a way to avoid repetition. :)

**Comment by hellobrophy** [comment]
Sorry man, I totally didn't read the code properly. It works fine. Apologies for the inconvenience!
