### ISSUE TITLE
format question

### ISSUE THREAD

**Issue by nicmare** [jylauril/jquery-runner#2]
i am using it as a countdown script starting at 15 minutes without miliseconds:
15:00

when it reaches minute one, it looks like this (seconds only):
59

can i keep the zero minutes?? like this:
00:59

**Comment by jylauril** [comment]
Then you could just inspect the current value and modify it if needed:

``` javascript
$('#runner').runner({
    startAt: 15 * 60 * 1000,
    countdown: true,
    milliseconds: false,
    format: function(value, oldFormatter, ms) {
        value = oldFormatter(value, ms).split(':');
        if (value.length < 2) value.unshift('00');
        return value.join(':');
    }
});
```

**Comment by nicmare** [comment]
thank you! but…hmm, seems not to work :(

**Comment by jylauril** [comment]
Ah, good catch. There's an actual bug. :)
Let me fix that in a minute.

**Comment by jylauril** [comment]
Update the jquery.runner.js and it should work.

**Comment by nicmare** [comment]
yessss… now it works :-) thank you !

**Comment by nicmare** [comment]
sorry, have one question left. i am using the script as countdown with leading double zero. it works great this way. at the end of the game i want to show the lapsed time. so i am fetching the time with 
var time = $('.stopwatch').runner('lap'); 
which returns me this format:
00:11 
(0 minutes and 11 seconds). can i split those minutes and seconds? like this:
0 Minutes and 11 Seconds

**Comment by jylauril** [comment]
Well yea, it is basic Javascript string manipulation after that.

You can split the time with the colon character and take parseInt value from them and display them as you wish.

``` javascript
var time = $('.stopwatch').runner('lap').split(':');
var mins = parseInt(time[0]);
var secs = parseInt(time[1]);

alert("Last lap: " + mins + " Minutes and " + secs + " Seconds");
```

**Comment by nicmare** [comment]
allright, thank you and sorry. i am not that js expert ;-)

**Comment by DeployIsComing** [comment]
Im trying to format with this structure hh:mm:ss with leading zeros eg. 00:00:40. The default format do not include the leading zeros when the runner is counting just the second. Unfortunately the documentation did not help to much. Anybody has a glimpse how to overcome this problem?

**Comment by DeployIsComing** [comment]
I just want to say that the above issue I created a solution in the same day, for those who are facing the same problem here is the code:

[code]

<script src="javascripts/lib/jquery.runner.js"></script>

<script>
        var flagAlert = false;
                                function showAlert()
                                {
                                    if (flagAlert == false)
                                    {
                                        alert('Seu tempo acabou');
                                        flagAlert = true;
                                    }
                                }
                                $('.runner').runner({
                                    autostart: true,
                                    countdown: true,
                                    milliseconds: false,
                                    startAt: <?php echo $_POST['tempo'] * 60000; ?>,
                                    stopAt: 0,
                                    format: function millisecondsToString(milliseconds) {
                                        var oneHour = 3600000;
                                        var oneMinute = 60000;
                                        var oneSecond = 1000;
                                        var seconds = 0;
                                        var minutes = 0;
                                        var hours = 0;
                                        var result;
                                        if (milliseconds >= oneHour) {
                                            hours = Math.floor(milliseconds / oneHour);
                                        }
                                        milliseconds = hours > 0 ? (milliseconds - hours * oneHour) : milliseconds;
                                        if (milliseconds >= oneMinute) {
                                            minutes = Math.floor(milliseconds / oneMinute);
                                        }
                                        milliseconds = minutes > 0 ? (milliseconds - minutes * oneMinute) : milliseconds;
                                        if (milliseconds >= oneSecond) {
                                            seconds = Math.floor(milliseconds / oneSecond);
                                        }
                                        milliseconds = seconds > 0 ? (milliseconds - seconds * oneSecond) : milliseconds;
                                        if (hours > 0) {
                                            result = (hours > 9 ? hours : "0" + hours) + ":";
                                        } else {
                                            result = "00:";
                                        }
                                        if (minutes > 0) {
                                            result += (minutes > 9 ? minutes : "0" + minutes) + ":";
                                        } else {
                                            result += "00:";
                                        }
                                        if (seconds > 0) {
                                            result += (seconds > 9 ? seconds : "0" + seconds);
                                        } else {
                                            result += "00";
                                        }
                                        
                                        return result;
                                    }  
                                    
                                }).on('runnerFinish', function(eventObject, info) {
                                    showAlert();
                                    document.forms['form_1'].submit();
                                });
                                function beforeSubmit()
                                {
                                    if (confirm('Tem certeza que deseja finalizar o simulado?')) {
                                        $("#current_time").val($('.runner').runner('getCurrentTime'));
                                        document.forms['form_1'].submit();
                                    }
                                    else
                                        return false;
                                }
</script>

[/code]

It works smoothly.

**Comment by de3f** [comment]
Hello, tresloukadu. It is very sad, that you removed the code of Your solution :)

**Comment by DeployIsComing** [comment]
Sorry man I was trying to indent the code here but i suspect the tags I used were stripped by git system. Here is the solution: http://pastebin.com/WZ1BA2nD

**Comment by TangoSucka44** [comment]
To anyone coming to this recently, there is a much quicker solution:

Line 59 of the original jquery.runner.js file is as follows:

if ((value || i > 1 || output) && (i !== len - 1 || ms)) {
        output += (output ? separator[i] : '') + pad(value);
      }

Change this section to the following:

if ((value || i > 1 || output) && (i !== len - 1 || ms)) {
        output += (output ? separator[i] : '') + pad(value);
      }

You may need to create a local version of the .js file so that you can edit the code.

**Comment by vijay1189** [comment]
Hi, can i get the output of timer starts only with seconds instated of milliseconds.
I want to get rid of milliseconds while starting my clock.
Thanks in advance.
