### ISSUE TITLE
Plugin is not working!

### ISSUE THREAD

**Issue by asharirfan** [jylauril/jquery-runner#22]
Hi,

I tried creating a simple example with the help of this plugin. But it didn't work.
Can you please tell me what is it that I am doing wrong?

I am attaching the file with my ticket.
[index.txt](https://github.com/jylauril/jquery-runner/files/394708/index.txt)

Any help would be greatly appreciated.
Best regards,
Ashar

**Comment by bees4ever** [comment]
Hi,

I don't know, if this question has been solved yet. If not, I can give you a hint what was wrong:

1. The import of the jquery file had a syntax error (to many <script> tags):

`<script type="text/javascript" src="<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>"></script>`

2. Some browsers don't allow to use js files if they was sent with a header by mime-type text/html 
![bildschirmfoto 2017-01-31 um 15 43 58](https://cloud.githubusercontent.com/assets/21102167/22469385/1fe702b4-e7cc-11e6-9142-d134092b665d.png)

3. You used two different ids of your timer element

```javascript
$('#time').runner();
$('#myButton').click(function() {
$('#runner').runner('start');
});
```


Here is a working example
[answer.txt](https://github.com/jylauril/jquery-runner/files/742241/answer.txt)


// Benny
