### ISSUE TITLE
Runner UI is not working for me

### ISSUE THREAD

**Issue by malhayek2012** [jylauril/jquery-runner#3]
Hi
I am trying to use the runner UI but it is not working for me at all.

I have follower the instruction but still not finding where I went wrong. I have posted a detailed issue on the following link.http://forum.jquery.com/topic/runner-ui-does-not-run

I will appreciate it if you can help me this issue.

Thanks

**Comment by jylauril** [comment]
Thanks for bringing this up, I went through the code and found a small problem with the logic. So yeah, there was an actual bug. I fixed it and released a new version (2.1.2), so go grab that and try again. :)
