### ISSUE TITLE
Bug in runnerlap event

### ISSUE THREAD

**Issue by ganesanarun** [jylauril/jquery-runner#4]
$("#runner").runner("lap") did not return the current time instead it shows as

[object object] in the alert mesage

**Comment by reignsly** [comment]
The return value is an object try console instead of alert.

**Comment by jylauril** [comment]
There was a small bug regarding that. Forgot to return the lap value when lap method was called. Fixed now in 2.1.3.

**Comment by ganesanarun** [comment]
thank you for your kind response.i don't know about to console the return
value can you please give solution to me

**Comment by jylauril** [comment]
Ignore @reignsly's comment, the issue is now fixed. You can use it now like you were trying to use it in the first place. Just grab the latest version from there: https://raw.github.com/jylauril/jquery-runner/master/build/jquery.runner-min.js

**Comment by ganesanarun** [comment]
thanks buddy.i will try

**Comment by ganesanarun** [comment]
it's working thanks.here is one suggestion if i set the start time(startAt)
as 1 minute and run the timer after 9 seconds ,i tried to show my lap time
then it will show only 9 seconds instead of 01:09.i think you just need to
add start time(startAt) and lap time and then only you should return the
lap time(sorry if anything i said wrong)

**Comment by jylauril** [comment]
You raise a very good point. The first time the lap method is called it should take under consideration the start time as well. I will implement this feature right away.

**Comment by jylauril** [comment]
Grab the latest version from here: https://raw.github.com/jylauril/jquery-runner/2.2.0/build/jquery.runner-min.js

**Comment by ganesanarun** [comment]
okay Laurila....thank you
