### ISSUE TITLE
The method "on" is missing when im trying "}).on('runnerFinish', function(eventObject, info) {".

### ISSUE THREAD

**Issue by reignsly** [jylauril/jquery-runner#5]
Uncaught TypeError: Object [object Object] has no method 'on' 
Code:
$('#runner').runner({
countdown: true,
startAt: 12 \* 60 \* 1000,
stopAt: 0
}).on('runnerFinish', function(eventObject, info) {
alert('The eggs are now hard-boiled!');
});

The timer runner is running but i want to do something when the runner finish,

**Comment by jylauril** [comment]
You need to give more info than that quote.. I still have no idea what you're trying to call that on-method for.

**Comment by reignsly** [comment]
Oh sorry, I'm trying the example and Im getting an error 
Uncaught TypeError: Object [object Object] has no method 'on' 
Code:
$('#runner').runner({
    countdown: true,
    startAt: 12 \* 60 \* 1000,
    stopAt: 0
}).on('runnerFinish', function(eventObject, info) {
    alert('The eggs are now hard-boiled!');
});

-> I used

<script src="jquery.runner.js" type="text/javascript"></script>

**Comment by reignsly** [comment]
The timer runner is running but i want to do something when the runner finish,

**Comment by reignsly** [comment]
I already solved my own problem. The on method was not present at the old version of jquery.js. I used the new version(http://code.jquery.com/jquery-1.9.1.js) and it works fine.
Thanks.

**Comment by jylauril** [comment]
Ah yes, that's a good point. In older jQuery versions it was still .bind() instead of .on().
