### ISSUE TITLE
format question

### ISSUE THREAD

**Issue by ghost** [jylauril/jquery-runner#6]
Hi guy,
I'm trying to use the format 00:00:00, but it's not working with me..
Here it's give an error "Uncaught TypeError: object is not a function"
Can u give me a help?

Thanks!

**Comment by ghost** [comment]
Hey man, I found the solution.. It's not necessary anymore .. 

Thaaaaaaaaaaaaanks :)

**Comment by jylauril** [comment]
I'm glad you got it sorted out. :)

**Comment by brucfo** [comment]
How you solution this problem? Can you share it to us?

**Comment by ghost** [comment]
Hi @brucfo , I have used this solution: http://pastebin.com/WZ1BA2nD
Hope that helps you! Hugs. (:

**Comment by brucfo** [comment]
Hi @thiagodamico , this really helped me, thanks for sharing!
