### ISSUE TITLE
Publish on npm?

### ISSUE THREAD

**Issue by le717** [jylauril/jquery-runner#9]
Hello!
I am using your excellent runner in a small soon-to-be-published project, and I was wondering if you might consider [posting](https://www.npmjs.org/doc/cli/npm-publish.html) future versions on [npm](https://www.npmjs.org/).

Take care!

**Comment by jylauril** [comment]
Done. https://www.npmjs.org/package/jquery.runner

**Comment by le717** [comment]
Thank you! :smiley: BTW, the aforementioned project can be found at [le717/landslides](https://github.com/le717/landslides#readme). You'd be surprised how much the timer has added to it. :stuck_out_tongue:
